### ISSUE TITLE
All containers in the same environment return 403 or 404

### ISSUE THREAD

**Issue by JohnFasc** [microsoft/azure-container-apps#301]
### This issue is a: 
- [x] bug report -> please search issues before submitting

### Issue description
All of my containers return 403 or 404 after I created a new revision in multi revision mode, then switched the traffic to the new revision and deactivated the old one. 

the ingress setting and everything else seem to be normal and also worked before the new revision. The revision itself is also running normally. 

I use this script to switch traffic after and initial delay after the deployment

This is the powershell script i created: 

```
$response = az containerapp revision list --name <containerapp> --resource-group <resourcegroup>
$Revisions = $response | ConvertFrom-Json

$NewRevision=$Revisions[$Revisions.Count - 1].name
$OldRevision=$Revisions[$Revisions.Count - 2].name

az containerapp ingress traffic set -n <containerapp> -g <resourcegroup> --revision-weight $NewRevision=100
az containerapp revision deactivate --resource-group <resourcegroup> --revision  $OldRevision
```

### Steps to reproduct
1. Create at least 2 revisions in multi revision mode
2. Run the script and call the container

**Expected behavior** 
Normally the containers should switch the traffic and work as expected. 

**Actual behavior** [What actually happened.]

No container is responding
![image](https://user-images.githubusercontent.com/73105921/177572347-c7b354be-b590-423a-8d96-03eef950cb82.png)

**Comment by torosent** [comment]
Hi. The issue was caused by a bug in our control plane. We fixed your cluster and working to solve the root cause as well.

**Comment by JohnFasc** [comment]
Thanks for the feedback. All my containers are responding again. Is there anything I can do to prevent this from happening again? We want to launch the first productive version next week on container apps, and I have some concerns with the reliability of the system.

**Comment by torosent** [comment]
Hi, We are still exploring the root cause of the issue you had in your environment. We haven't encounter it until now. We will add this specific issue to our self healing components to mitigate it and I will update you as soon as I have more information. If you see any issues, you can open a support ticket with sev A or email to acasupport at microsoft dot com

**Comment by maikelvanhaaren** [comment]
@torosent any possibility that this is issue is still out there? Got the same issue

**Comment by torosent** [comment]
Can you please send the environment details and subscription id to `acasupport at microsoft dot com`. I will open a ticket for the on call engineer.

**Comment by maikelvanhaaren** [comment]
@torosent email sent!
