### ISSUE TITLE
Deployment using secret and  `keyVaultUrl` reference with system identity stopped working

### ISSUE THREAD

**Issue by andmos** [microsoft/azure-container-apps#722]
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description
Our Container App setup contains a simple application using a secret referencing a key vault:
```json
        "configuration": {
            "secrets": [
                {
                    "name": "auth0-client-secret",
                    "keyVaultUrl": "https://xxxxxxx.vault.azure.net/secrets/Auth0ClientSecret",
                    "identity": "system"
                },
```

Which was created _after_ the container app itself, as noted in this issue: https://github.com/microsoft/azure-container-apps/issues/608

To update and deploy the app, we use the following `az containerapp` command:
```sh
          az containerapp update \
          --resource-group ${{ env.AZURE_CONTAINER_APP_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
          --image "${{ env.CONTAINER_IMAGE_APP }}:${{ steps.version.outputs.version }}" \
          --set-env-vars ${{ env.ASPNETCORE_APP_ENVIRONMENT }} ${{ steps.deployment-secretrefs.outputs.variables }}
```

Where `${{ steps.deployment-secretrefs.outputs.variables }}` extracts to `Auth0__ClientSecret=secretref:auth0-client-secret`, hence a reference to the above mentioned secret referencing the key vault.

This has worked perfectly up until yesterday.
Then we started to receive the following error:

```
ERROR: (WebhookInvalidParameterValue) The following field(s) are either invalid or missing. Invalid value: "auth0-client-secret": Unable to get value using Managed identity system for secret auth0-client-secret. Error: Unable to fetch secret 'auth0-client-secret' using Managed identity 'system': configuration.secrets.
```

The same error also occur when trying to edit or create a new revision in the portal:
```
Failed to deploy new revision: The following field(s) are either invalid or missing. Invalid value: "auth0-client-secret": Unable to get value using Managed identity system for secret auth0-client-secret. Error: Unable to fetch secret 'auth0-client-secret' using Managed identity 'system': configuration.secrets.
```

The last working timestamp is `Mon, 17 Apr 2023 13:01:26 GMT`, while first broken timestamp is `Tue, 18 Apr 2023 04:41:20 GMT`.

### Steps to reproduce
1. Create an container app environment
2. Create an container app in this environment
3. Create a key vault with a test secret in the same resource group as container app
4. Create a secret with `Key Vault Reference` pointing to the secret in the key vault and `Managed identity` as `System assigned`
5. Add a reference to the secret when adding environmental variables to the app with `--set-env-vars Auth0__ClientSecret=secretref:auth0-client-secret` or select it from the dropdown in the portal
6. Try to deploy

**Expected behavior** [What you expected to happen.]
Expected the ` az containerapp update` command or revision update in the portal to execute without error.
```

```
**Actual behavior** [What actually happened.]
Resulting in the errors above:

```
ERROR: (WebhookInvalidParameterValue) The following field(s) are either invalid or missing. Invalid value: "auth0-client-secret": Unable to get value using Managed identity system for secret auth0-client-secret. Error: Unable to fetch secret 'auth0-client-secret' using Managed identity 'system': configuration.secrets.
```
```
Failed to deploy new revision: The following field(s) are either invalid or missing. Invalid value: "auth0-client-secret": Unable to get value using Managed identity system for secret auth0-client-secret. Error: Unable to fetch secret 'auth0-client-secret' using Managed identity 'system': configuration.secrets.
```

### Additional context
Occur both with CLI and portal.

Container App Environment and Container App was created before the key vault and secret referencing it.

**Comment by andmos** [comment]
If we try to create a new secret side-by-side which doesn't reference key vault (the thought is to create a regular secret with the value from the key store as a workaround) we get the same error:
```
Failed to update secrets: The following field(s) are either invalid or missing. Invalid value: "auth0-client-secret": Unable to get value using Managed identity system for secret auth0-client-secret. Error: Unable to fetch secret 'auth0-client-secret' using Managed identity 'system': configuration.secrets.

```

**Comment by andmos** [comment]
Could this be related to https://github.com/microsoft/azure-container-apps/issues/395#issuecomment-1513542027?

**Comment by sanchitmehta** [comment]
Hello, we identified an issue with one of latest Platform releases. We are working to fix this ASAP, we would share an update once the fix has been deployed

**Comment by andmos** [comment]
Great @sanchitmehta!

**Comment by andmos** [comment]
In case anyone else is blocked by this, our workaround was to recreate the app and create a regular secret with the value populated with the value from the key vault with Terraform.

**Comment by bstriche** [comment]
still experiencing this issue on an existing container app that has added a secret with a keyvault reference

**Comment by chriswue** [comment]
@sanchitmehta This feature has been broken again for a month now: https://github.com/microsoft/azure-container-apps/issues/739 - could someone please fix it for good?

**Comment by jason-berk-k1x** [comment]
same

>The behavior of this command has been altered by the following extension: containerapp
(InvalidParameterValueInContainerTemplate) The following field(s) are either invalid or missing. Field 'configuration.secrets' is invalid with details: 'Invalid value: "instrumentation-key": Unable to get value using Managed identity system for secret instrumentation-key. Error: unable to fetch secret 'instrumentation-key' using Managed identity 'system'';.

trying to update an ACA app to set the instrumentation key as an env variable:

```
resource "azurerm_role_assignment" "app_shared_kv_assignment" {
  principal_id                  = azurerm_container_app.app.identity[0].principal_id
  role_definition_name  = "Key Vault Secrets User"
  scope                            = data.azurerm_key_vault.shared_kv.id
}
```
