### ISSUE TITLE
Docs Unclear on Internal DNS Configuration

### ISSUE THREAD

**Issue by ay-azara** [microsoft/azure-container-apps#727]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Alright, this might just be a PEBKAC issue but I promise I've gone over the docs and can't find what I need. If I deploy a Container App to a VNET and have it resolve an internal address like foo.internal.local it fails. This is because it's not using the name servers configured for the VNET. Doing a `dig foo.internal.local` shows localhost as the nameserver so this being handled by the underlying infrastructure.

I would expect the container to use the internal DNS servers automatically. When I console in and run `dig @internal_dns_server foo.internal.local` it resolves the internal IP so it's not that it can't communicate with the internal DNS server at all.

Are containers supposed to just hard code the name servers to resolv.conf or is there an environment variable that needs set? I see that a DNS suffix can be set when [Ingress is enabled ](https://learn.microsoft.com/en-us/azure/container-apps/networking#ingress-configuration) but these containers aren't expecting Ingress traffic.

Sorry if I'm missing something obvious here.

**Comment by jemrpo** [comment]
I'm having the same issue right now, it was working perfectly fine in one environment I deployed last week manually. This week I deployed one using automation (Terraform + azapi) and no longer able to resolve internal records.

Have a case open with Microsoft, tried lots of different combinations but cannot replicate the working configuration anymore.

**Comment by ay-azara** [comment]
Yeah. After I submitted this ticket I tried hardcoding the internal DNS server in `/etc/resolv.conf` but couldn't write to the file cause it's immutable.

**Comment by jemrpo** [comment]
I tested this morning on two different environments and is working fine. I made no changes to my configuration. I suspect there was a change on Azure's end.

**Comment by ay-azara** [comment]
Wish I had your luck. Getting this to work has been a bit of a saga for me. Just tried re-creating the Container App Env thinking things might've improved since I last time and got a new error "Can't deploy to a delegated subnet" even though that subnet was configured for `Microsoft.App/environments` and worked previously. After removing the delegation and re-creating again it failed with `The resource provision operation did not complete within the allowed timeout period.` which took about an error. =/

**Comment by cachai2** [comment]
Is everyone running into this issue on the workload profiles environments or is anyone running into this on a Consumption only environment? There was a bug we've identified on the workload profiles environments that seemed to be causing this issue, and we have a fix which should be rolled out in a few weeks. If after a few weeks, you are still seeing these issues or if you're seeing it on Consumption only environments, please re-ping the thread.

**Comment by cachai2** [comment]
> Wish I had your luck. Getting this to work has been a bit of a saga for me. Just tried re-creating the Container App Env thinking things might've improved since last time and got a new error "Can't deploy to a delegated subnet" even though that subnet was configured for `Microsoft.App/environments` and worked previously. After removing the delegation and re-creating again it failed with `The resource provision operation did not complete within the allowed timeout period.` which took about an hour. =/

@ay-azara looking over your previous comment, Consumption only environments don't support deploying to a delegated subnet. The second error you are running into sounds like a potential transient deployment issue. Can you please try again and let us know if you are still running into the same issue?

**Comment by redoz** [comment]
@ay-azara Were you able to figure something out? I think we're having the same issue, the internal DNS (that defaults to 10.0.0.2) in our ACA isn't forwarding to our private DNS.

**Comment by bramvdklinkenberg** [comment]
We have a hub spoke topolgy, with vnet manager managing the hub and spoke routing. We also have a private dns resolver and vpn gateway for a p2s connection. 
When I am connected via vpn I can resolve the private dns endpoints, but when we deploy our container App (private app environment) it automatically uses 10.0.0.2 as nameserver and can't resolve the private endpoints, because it resolves to the public endpoint of the services. When I do a nslookup from within the container using and use dns resolver for the lookup then it resolves fine to the private endpoint (ip).

**Comment by jemrpo** [comment]
VNET integration is working fine for me, @bramvdklinkenberg which service endpoints are you trying to reach? I had a similar issue and it was fixed when I unchecked the KV service from the Service Endpoint Subnet configuration.

**Comment by bramvdklinkenberg** [comment]
@jemrpo I don't use service endpoints but private endpoints. 

This resolves to the pubic endpoint (ip) of the Kusto cluster:
nslookup <ADX name>.<REGION>.kusto.windows.net
Server:         10.0.0.2
Address:        10.0.0.2#53


This resolves to the private endpoint (ip) of the Kusto cluster:
nslookup adx-nonprod.<REGION>.kusto.windows.net 10.2.xx.x
Server:         10.2.xx.x
Address:        10.2.xx.x#53

**Comment by mdepedrof** [comment]
Im in the same situation. From within container dont use the VNET Custom DNS and this make that the container reolve all private endpoint as public endpoint not with private ips. If go console within the container and do nslookp server and set the correct dns server all resolves perfect so the connectivity are ok. The problem is that the container not get the correct DNs server by default.
