### ISSUE TITLE
Container App Vnet Integration Issue

### ISSUE THREAD

**Issue by Marveric-18** [microsoft/azure-container-apps#782]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The current setup for Container Apps with Vnet Integration, which includes applying ingress rules to allow only Vnet traffic, is not accepting traffic from the Virtual Network Gateway via the Point-to-Site (P2S) connection.

### Steps to reproduce
1. Create a Resource Group.
2. Create a Virtual Network. (10.0.0.0/24)
3. Create two Subnets inside Virtual Network. 
      i. Gateway Subnet (10.0.0.0/27)
     ii. WebApp Subnet (10.0.3.0/27)
5. Create a Virtual Network Gateway with Vnet and Gateway Subnet.
6. Configure P2S Connection.
7. Create a Container App Environment with Vnet Integration and internal-only settings.
8. Create a Container APP with the above Container App environment.

**Expected behavior** 
When connected to the VPN through VPN gateway P2S connection, should be able to access the Container App
**Actual behavior** 
When connected as mentioned above, unable to reach out to Container App

**Screenshots**         
<img width="691" alt="Screenshot 2023-06-10 at 1 43 13 PM" src="https://github.com/microsoft/azure-container-apps/assets/32873264/dab1011a-b63a-442d-94ff-994283b241f2">

<img width="1512" alt="Screenshot 2023-06-10 at 1 45 04 PM" src="https://github.com/microsoft/azure-container-apps/assets/32873264/511c7fe9-c922-449f-a6c9-c788893cc419">

<img width="1512" alt="Screenshot 2023-06-10 at 1 46 01 PM" src="https://github.com/microsoft/azure-container-apps/assets/32873264/1c48ce40-f40e-4de6-ac37-eeed817f7699">

### Additional context
Issue while working through Portal

**Comment by torosent** [comment]
Hi, Did you setup a private DNS zone? otherwise, you can't resolve the address

**Comment by jvesthansen1990** [comment]
Created the following:

![image](https://github.com/microsoft/azure-container-apps/assets/42712599/002e5648-6d00-4a1f-81c3-01def9ef8c16)

**Comment by Marveric-18** [comment]
Thanks, Yes I tried adding the private DNS zone, but I was not able to figure out the configuration, I'll try once again.

**Comment by Marveric-18** [comment]
As discussed, I created a DNS zone: westus2.azurecontainerapps.io
I also added a record set for the container app IP.
So the whole DNS looks like this: container-appv2.delightfulground-e60873cf.westus2.azurecontainerapps.io/

Still, while connected to my VPN gateway from the Azure client, unable to connect to my app.

![Screenshot (10)](https://github.com/microsoft/azure-container-apps/assets/32873264/4c5ce1ba-2493-40b2-b7cc-d30c10d6d33b)

![Screenshot (12)](https://github.com/microsoft/azure-container-apps/assets/32873264/09e98f13-d8db-423f-b0b2-b99b98eeedb7)

![Screenshot (13)](https://github.com/microsoft/azure-container-apps/assets/32873264/8d54a6e0-b5be-4c90-84f3-3305cc4ca216)

**Comment by s-bali** [comment]
+1
I am also having the same issue.

**Comment by s-tharani** [comment]
+1 Having the same issue while setting up the containerized setup for my web app. But the same thing works fine for container instance and not for container apps.

**Comment by hyaman** [comment]
I'm encountering an identical issue. Our configuration mirrors yours precisely, with the exception that we're attempting to establish a connection from within the container application to our on-premises SQL server through a site-to-site VPN. Regrettably, we haven't achieved success in this endeavour.

Thanks
HY.

**Comment by Freshchris01** [comment]
@Marveric-18 My comment relates to the details, you posted on July 15.
I was working a lot with Container Apps in VNets and Virtual Network Gateway as point-to-site VPN.
For me, this looks like a DNS issue. Can you resolve the FQDN to the private IP while you are connected to the VPN?
`nslookup container-appv2.delightfulground-e60873cf.westus2.azurecontainerapps.io`

I solved this issue by using a private DNS resolver and adding its IP to the VNet DNS server settings.

**Comment by eduardomb-aw** [comment]
I'm having the same issue. I deployed a new container app using the quickstart image "Simple hello word container". A new container app environment was also created using an existing virtual network that is peered to my on-premise network. A new subnet is created with a /23 CDIR block and I select "Internal" for "Virtual IP".

After deployment is completed, I understand the FQDN would not be resolved yet if no Private DNS zone is created. However, shouldn't the app be accessible via the Container App Environment's static IP address?

![image](https://github.com/microsoft/azure-container-apps/assets/153018578/33d3222e-5431-4502-94c5-058739e4fb08)

<img width="503" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/153018578/ae206dfe-9188-4370-a01f-30f67389def4">


<img width="477" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/153018578/45d877d6-4588-48b7-a7ab-977e2a130ae5">

**Comment by eduardomb-aw** [comment]
In addition to the info provided above, I have tried the following:

Deployed a new VM to the same VNET used above and ran Connection troubleshoot on the VNET between the new VM and the target IP. Here are the results:

<img width="366" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/153018578/c2e8b803-70a2-4026-968b-ee444be55ebd">

I've also logged in on the VM and tried browsing to the same target IP and got the same Access denied message:

<img width="1082" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/153018578/e40a66c2-38ff-4bda-aa76-b8305d09174e">

**Comment by PBeckerr** [comment]
Private DNS Resolver works but at 180$ per Month its not really a alternative....

**Comment by nitinpaik** [comment]
+1
Both my container app and VM are on the same vnet. I am able to connect to the container from inside the VM using private IP. But I am not able to connect via static IP.

**Comment by carlgleisner** [comment]
I just want to check up on this since it seems that this is still an issue.

Will subscribe to this issue but I'm truly sad that this is blocking our plans at work.

Too bad that this is (from the looks of it) not attended ☹️
